{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 104857600,
      "rowLimit": 1000
     },
     "inputWidgets": {},
     "nuid": "5ca7035d-99a4-42e0-bf53-6bbe7bf12bcb",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "-- COURSES BRONZE DATA QUALITY VALIDATION\n",
    "\n",
    "WITH duplicate_course AS (\n",
    "    -- Identify duplicate course business keys\n",
    "    SELECT\n",
    "        code_module,\n",
    "        code_presentation,\n",
    "        COUNT(*) AS duplicate_count\n",
    "    FROM oulad.oulad_bronze.courses_bronze\n",
    "    GROUP BY\n",
    "        code_module,\n",
    "        code_presentation\n",
    "    HAVING COUNT(*) > 1\n",
    "),\n",
    "\n",
    "duplicate_exact AS (\n",
    "    -- Identify exact duplicate records\n",
    "    SELECT\n",
    "        code_module,\n",
    "        code_presentation,\n",
    "        module_presentation_length,\n",
    "        COUNT(*) AS duplicate_count\n",
    "    FROM oulad.oulad_bronze.courses_bronze\n",
    "    GROUP BY\n",
    "        code_module,\n",
    "        code_presentation,\n",
    "        module_presentation_length\n",
    "    HAVING COUNT(*) > 1\n",
    "),\n",
    "\n",
    "validation_results AS (\n",
    "\n",
    "    -- Volume check\n",
    "    SELECT\n",
    "        'courses_bronze' AS table_name,\n",
    "        'Row count' AS check_name,\n",
    "        'VOLUME' AS dq_category,\n",
    "        COUNT(*) AS total_rows,\n",
    "        0 AS failed_rows,\n",
    "        0.00 AS failure_pct,\n",
    "        'Table should contain records' AS expected_value,\n",
    "        CASE\n",
    "            WHEN COUNT(*) > 0 THEN 'PASS'\n",
    "            ELSE 'FAIL'\n",
    "        END AS status\n",
    "    FROM oulad.oulad_bronze.courses_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- NULL checks\n",
    "    SELECT\n",
    "        'courses_bronze',\n",
    "        'Missing code_module',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(code_module IS NULL),\n",
    "        ROUND(\n",
    "            COUNT_IF(code_module IS NULL) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        '0% missing; mandatory key',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(code_module IS NULL) = 0 THEN 'PASS'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.courses_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'courses_bronze',\n",
    "        'Missing code_presentation',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(code_presentation IS NULL),\n",
    "        ROUND(\n",
    "            COUNT_IF(code_presentation IS NULL) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        '0% missing; mandatory key',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(code_presentation IS NULL) = 0 THEN 'PASS'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.courses_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'courses_bronze',\n",
    "        'Missing module_presentation_length',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(module_presentation_length IS NULL),\n",
    "        ROUND(\n",
    "            COUNT_IF(module_presentation_length IS NULL) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'Length should be populated',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(module_presentation_length IS NULL) = 0 THEN 'PASS'\n",
    "            WHEN COUNT_IF(module_presentation_length IS NULL) * 100.0 / COUNT(*) <= 1\n",
    "                THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.courses_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- Uniqueness checks\n",
    "    SELECT\n",
    "        'courses_bronze',\n",
    "        'Duplicate course business key',\n",
    "        'UNIQUE',\n",
    "        COUNT(*),\n",
    "        COALESCE(\n",
    "            (SELECT SUM(duplicate_count - 1) FROM duplicate_course),\n",
    "            0\n",
    "        ),\n",
    "        ROUND(\n",
    "            COALESCE(\n",
    "                (SELECT SUM(duplicate_count - 1) FROM duplicate_course),\n",
    "                0\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        '0% duplicate code_module + code_presentation',\n",
    "        CASE\n",
    "            WHEN COALESCE(\n",
    "                (SELECT SUM(duplicate_count - 1) FROM duplicate_course),\n",
    "                0\n",
    "            ) = 0 THEN 'PASS'\n",
    "            WHEN COALESCE(\n",
    "                (SELECT SUM(duplicate_count - 1) FROM duplicate_course),\n",
    "                0\n",
    "            ) * 100.0 / COUNT(*) <= 1 THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.courses_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'courses_bronze',\n",
    "        'Exact duplicate records',\n",
    "        'UNIQUE',\n",
    "        COUNT(*),\n",
    "        COALESCE(\n",
    "            (SELECT SUM(duplicate_count - 1) FROM duplicate_exact),\n",
    "            0\n",
    "        ),\n",
    "        ROUND(\n",
    "            COALESCE(\n",
    "                (SELECT SUM(duplicate_count - 1) FROM duplicate_exact),\n",
    "                0\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        '0% duplicate records',\n",
    "        CASE\n",
    "            WHEN COALESCE(\n",
    "                (SELECT SUM(duplicate_count - 1) FROM duplicate_exact),\n",
    "                0\n",
    "            ) = 0 THEN 'PASS'\n",
    "            WHEN COALESCE(\n",
    "                (SELECT SUM(duplicate_count - 1) FROM duplicate_exact),\n",
    "                0\n",
    "            ) * 100.0 / COUNT(*) <= 1 THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.courses_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- Format checks for text fields\n",
    "    SELECT\n",
    "        'courses_bronze',\n",
    "        'Invalid code_module format',\n",
    "        'TYPE / FORMAT',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(\n",
    "            code_module IS NOT NULL\n",
    "            AND TRIM(code_module) = ''\n",
    "        ),\n",
    "        ROUND(\n",
    "            COUNT_IF(\n",
    "                code_module IS NOT NULL\n",
    "                AND TRIM(code_module) = ''\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'code_module must contain a value',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(\n",
    "                code_module IS NOT NULL\n",
    "                AND TRIM(code_module) = ''\n",
    "            ) = 0 THEN 'PASS'\n",
    "            WHEN COUNT_IF(\n",
    "                code_module IS NOT NULL\n",
    "                AND TRIM(code_module) = ''\n",
    "            ) * 100.0 / COUNT(*) <= 1 THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.courses_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'courses_bronze',\n",
    "        'Invalid code_presentation format',\n",
    "        'TYPE / FORMAT',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(\n",
    "            code_presentation IS NOT NULL\n",
    "            AND TRIM(code_presentation) = ''\n",
    "        ),\n",
    "        ROUND(\n",
    "            COUNT_IF(\n",
    "                code_presentation IS NOT NULL\n",
    "                AND TRIM(code_presentation) = ''\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'code_presentation must contain a value',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(\n",
    "                code_presentation IS NOT NULL\n",
    "                AND TRIM(code_presentation) = ''\n",
    "            ) = 0 THEN 'PASS'\n",
    "            WHEN COUNT_IF(\n",
    "                code_presentation IS NOT NULL\n",
    "                AND TRIM(code_presentation) = ''\n",
    "            ) * 100.0 / COUNT(*) <= 1 THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.courses_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- Range check\n",
    "    SELECT\n",
    "        'courses_bronze',\n",
    "        'Invalid module_presentation_length range',\n",
    "        'RANGE',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(\n",
    "            module_presentation_length IS NOT NULL\n",
    "            AND module_presentation_length <= 0\n",
    "        ),\n",
    "        ROUND(\n",
    "            COUNT_IF(\n",
    "                module_presentation_length IS NOT NULL\n",
    "                AND module_presentation_length <= 0\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'module_presentation_length must be greater than 0',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(\n",
    "                module_presentation_length IS NOT NULL\n",
    "                AND module_presentation_length <= 0\n",
    "            ) = 0 THEN 'PASS'\n",
    "            WHEN COUNT_IF(\n",
    "                module_presentation_length IS NOT NULL\n",
    "                AND module_presentation_length <= 0\n",
    "            ) * 100.0 / COUNT(*) <= 1 THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.courses_bronze\n",
    ")\n",
    "\n",
    "SELECT\n",
    "    table_name,\n",
    "    check_name,\n",
    "    dq_category,\n",
    "    total_rows,\n",
    "    failed_rows,\n",
    "    failure_pct,\n",
    "    expected_value,\n",
    "    status\n",
    "FROM validation_results\n",
    "ORDER BY\n",
    "    CASE dq_category\n",
    "        WHEN 'VOLUME' THEN 1\n",
    "        WHEN 'NULL' THEN 2\n",
    "        WHEN 'UNIQUE' THEN 3\n",
    "        WHEN 'TYPE / FORMAT' THEN 4\n",
    "        WHEN 'RANGE' THEN 5\n",
    "        ELSE 6\n",
    "    END,\n",
    "    check_name;"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": null,
   "inputWidgetPreferences": null,
   "language": "sql",
   "notebookMetadata": {
    "pythonIndentUnit": 4,
    "sqlQueryOptions": {
     "applyAutoLimit": true,
     "catalog": "workspace",
     "metastore": null,
     "schema": "default"
    }
   },
   "notebookName": "check_courses_bronze.sql.dbquery.ipynb",
   "widgets": {}
  },
  "language_info": {
   "name": "sql"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
