{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 104857600,
      "rowLimit": 1000
     },
     "inputWidgets": {},
     "nuid": "29045c25-e12a-4ef3-8b2f-0b1c376baeb1",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "-- STUDENT INFO BRONZE DATA QUALITY VALIDATION\n",
    "\n",
    "WITH base AS (\n",
    "    SELECT *\n",
    "    FROM oulad.oulad_bronze.student_info_bronze\n",
    "),\n",
    "\n",
    "course_keys AS (\n",
    "    SELECT DISTINCT\n",
    "        TRIM(UPPER(code_module)) AS code_module,\n",
    "        TRIM(UPPER(code_presentation)) AS code_presentation\n",
    "    FROM oulad.oulad_bronze.courses_bronze\n",
    "),\n",
    "\n",
    "dq_results AS (\n",
    "\n",
    "    -- Volume check\n",
    "    SELECT\n",
    "        'student_info_bronze' AS table_name,\n",
    "        'Row count' AS check_name,\n",
    "        'VOLUME' AS dq_category,\n",
    "        COUNT(*) AS total_rows,\n",
    "        CASE\n",
    "            WHEN COUNT(*) = 0 THEN 1\n",
    "            ELSE 0\n",
    "        END AS failed_rows,\n",
    "        CASE\n",
    "            WHEN COUNT(*) = 0 THEN 100.00\n",
    "            ELSE 0.00\n",
    "        END AS failure_pct,\n",
    "        'Table should contain records' AS expected_value\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- NULL checks\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Missing code_module',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(code_module IS NULL),\n",
    "        ROUND(COUNT_IF(code_module IS NULL) * 100.0 / COUNT(*), 2),\n",
    "        '0% missing; mandatory key'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Missing code_presentation',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(code_presentation IS NULL),\n",
    "        ROUND(COUNT_IF(code_presentation IS NULL) * 100.0 / COUNT(*), 2),\n",
    "        '0% missing; mandatory key'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Missing id_student',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(id_student IS NULL),\n",
    "        ROUND(COUNT_IF(id_student IS NULL) * 100.0 / COUNT(*), 2),\n",
    "        '0% missing; mandatory key'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Missing gender',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(gender IS NULL),\n",
    "        ROUND(COUNT_IF(gender IS NULL) * 100.0 / COUNT(*), 2),\n",
    "        'Gender should normally be populated'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Missing region',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(region IS NULL),\n",
    "        ROUND(COUNT_IF(region IS NULL) * 100.0 / COUNT(*), 2),\n",
    "        'Region should normally be populated'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Missing highest_education',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(highest_education IS NULL),\n",
    "        ROUND(COUNT_IF(highest_education IS NULL) * 100.0 / COUNT(*), 2),\n",
    "        'Highest education should normally be populated'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Missing imd_band',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(imd_band IS NULL),\n",
    "        ROUND(COUNT_IF(imd_band IS NULL) * 100.0 / COUNT(*), 2),\n",
    "        'imd_band may be unavailable'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Missing age_band',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(age_band IS NULL),\n",
    "        ROUND(COUNT_IF(age_band IS NULL) * 100.0 / COUNT(*), 2),\n",
    "        'Age band should normally be populated'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Missing num_of_prev_attempts',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(num_of_prev_attempts IS NULL),\n",
    "        ROUND(COUNT_IF(num_of_prev_attempts IS NULL) * 100.0 / COUNT(*), 2),\n",
    "        'Previous attempts should normally be populated'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Missing studied_credits',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(studied_credits IS NULL),\n",
    "        ROUND(COUNT_IF(studied_credits IS NULL) * 100.0 / COUNT(*), 2),\n",
    "        'Studied credits should normally be populated'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Missing disability',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(disability IS NULL),\n",
    "        ROUND(COUNT_IF(disability IS NULL) * 100.0 / COUNT(*), 2),\n",
    "        'Disability should normally be populated'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Missing final_result',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(final_result IS NULL),\n",
    "        ROUND(COUNT_IF(final_result IS NULL) * 100.0 / COUNT(*), 2),\n",
    "        'Final result should normally be populated'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- Uniqueness checks\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Duplicate student-info business key',\n",
    "        'UNIQUE',\n",
    "        COUNT(*),\n",
    "        COUNT(*) - COUNT(DISTINCT CONCAT(\n",
    "            CAST(id_student AS STRING), '|',\n",
    "            TRIM(UPPER(code_module)), '|',\n",
    "            TRIM(UPPER(code_presentation))\n",
    "        )),\n",
    "        ROUND(\n",
    "            (COUNT(*) - COUNT(DISTINCT CONCAT(\n",
    "                CAST(id_student AS STRING), '|',\n",
    "                TRIM(UPPER(code_module)), '|',\n",
    "                TRIM(UPPER(code_presentation))\n",
    "            ))) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        '0% duplicate id_student + code_module + code_presentation'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Exact duplicate records',\n",
    "        'UNIQUE',\n",
    "        COUNT(*),\n",
    "        COUNT(*) - COUNT(DISTINCT\n",
    "            code_module,\n",
    "            code_presentation,\n",
    "            id_student,\n",
    "            gender,\n",
    "            region,\n",
    "            highest_education,\n",
    "            imd_band,\n",
    "            age_band,\n",
    "            num_of_prev_attempts,\n",
    "            studied_credits,\n",
    "            disability,\n",
    "            final_result\n",
    "        ),\n",
    "        ROUND(\n",
    "            (COUNT(*) - COUNT(DISTINCT\n",
    "                code_module,\n",
    "                code_presentation,\n",
    "                id_student,\n",
    "                gender,\n",
    "                region,\n",
    "                highest_education,\n",
    "                imd_band,\n",
    "                age_band,\n",
    "                num_of_prev_attempts,\n",
    "                studied_credits,\n",
    "                disability,\n",
    "                final_result\n",
    "            )) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        '0% exact duplicate records'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- Type and format checks\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Invalid id_student format',\n",
    "        'TYPE / FORMAT',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(\n",
    "            id_student IS NOT NULL\n",
    "            AND TRY_CAST(id_student AS BIGINT) IS NULL\n",
    "        ),\n",
    "        ROUND(\n",
    "            COUNT_IF(\n",
    "                id_student IS NOT NULL\n",
    "                AND TRY_CAST(id_student AS BIGINT) IS NULL\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'id_student must be numeric'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Invalid num_of_prev_attempts format',\n",
    "        'TYPE / FORMAT',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(\n",
    "            num_of_prev_attempts IS NOT NULL\n",
    "            AND TRY_CAST(num_of_prev_attempts AS INT) IS NULL\n",
    "        ),\n",
    "        ROUND(\n",
    "            COUNT_IF(\n",
    "                num_of_prev_attempts IS NOT NULL\n",
    "                AND TRY_CAST(num_of_prev_attempts AS INT) IS NULL\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'num_of_prev_attempts must be numeric'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Invalid studied_credits format',\n",
    "        'TYPE / FORMAT',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(\n",
    "            studied_credits IS NOT NULL\n",
    "            AND TRY_CAST(studied_credits AS INT) IS NULL\n",
    "        ),\n",
    "        ROUND(\n",
    "            COUNT_IF(\n",
    "                studied_credits IS NOT NULL\n",
    "                AND TRY_CAST(studied_credits AS INT) IS NULL\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'studied_credits must be numeric'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- Range checks\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Previous attempts below zero',\n",
    "        'RANGE',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(\n",
    "            TRY_CAST(num_of_prev_attempts AS INT) < 0\n",
    "        ),\n",
    "        ROUND(\n",
    "            COUNT_IF(\n",
    "                TRY_CAST(num_of_prev_attempts AS INT) < 0\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'num_of_prev_attempts >= 0'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Studied credits below zero',\n",
    "        'RANGE',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(\n",
    "            TRY_CAST(studied_credits AS INT) < 0\n",
    "        ),\n",
    "        ROUND(\n",
    "            COUNT_IF(\n",
    "                TRY_CAST(studied_credits AS INT) < 0\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'studied_credits >= 0'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- Source sentinel check\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Source sentinel (?) in imd_band',\n",
    "        'SENTINEL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(TRIM(imd_band) = '?'),\n",
    "        ROUND(\n",
    "            COUNT_IF(TRIM(imd_band) = '?') * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'Source may use ? for unavailable imd_band'\n",
    "    FROM base\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- Referential integrity check\n",
    "    SELECT\n",
    "        'student_info_bronze',\n",
    "        'Student without matching course presentation',\n",
    "        'FOREIGN KEY',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(\n",
    "            c.code_module IS NULL\n",
    "            OR c.code_presentation IS NULL\n",
    "        ),\n",
    "        ROUND(\n",
    "            COUNT_IF(\n",
    "                c.code_module IS NULL\n",
    "                OR c.code_presentation IS NULL\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'Every code_module + code_presentation should exist in courses_bronze'\n",
    "    FROM base b\n",
    "    LEFT JOIN course_keys c\n",
    "        ON TRIM(UPPER(b.code_module)) = c.code_module\n",
    "        AND TRIM(UPPER(b.code_presentation)) = c.code_presentation\n",
    ")\n",
    "\n",
    "SELECT\n",
    "    table_name,\n",
    "    check_name,\n",
    "    dq_category,\n",
    "    total_rows,\n",
    "    failed_rows,\n",
    "    failure_pct,\n",
    "    expected_value,\n",
    "    CASE\n",
    "        WHEN dq_category = 'VOLUME'\n",
    "             AND failed_rows = 0 THEN 'PASS'\n",
    "\n",
    "        WHEN dq_category = 'NULL'\n",
    "             AND failed_rows = 0 THEN 'PASS'\n",
    "\n",
    "        WHEN dq_category = 'NULL'\n",
    "             AND failed_rows > 0 THEN 'WARN'\n",
    "\n",
    "        WHEN dq_category = 'UNIQUE'\n",
    "             AND failure_pct = 0 THEN 'PASS'\n",
    "\n",
    "        WHEN dq_category = 'UNIQUE'\n",
    "             AND failure_pct <= 1 THEN 'WARN'\n",
    "\n",
    "        WHEN dq_category = 'UNIQUE'\n",
    "             AND failure_pct > 1 THEN 'FAIL'\n",
    "\n",
    "        WHEN dq_category = 'TYPE / FORMAT'\n",
    "             AND failed_rows = 0 THEN 'PASS'\n",
    "\n",
    "        WHEN dq_category = 'TYPE / FORMAT'\n",
    "             AND failed_rows > 0 THEN 'FAIL'\n",
    "\n",
    "        WHEN dq_category = 'RANGE'\n",
    "             AND failed_rows = 0 THEN 'PASS'\n",
    "\n",
    "        WHEN dq_category = 'RANGE'\n",
    "             AND failure_pct <= 1 THEN 'WARN'\n",
    "\n",
    "        WHEN dq_category = 'RANGE'\n",
    "             AND failure_pct > 1 THEN 'FAIL'\n",
    "\n",
    "        WHEN dq_category = 'SENTINEL'\n",
    "             AND failed_rows = 0 THEN 'PASS'\n",
    "\n",
    "        WHEN dq_category = 'SENTINEL'\n",
    "             AND failed_rows > 0 THEN 'WARN'\n",
    "\n",
    "        WHEN dq_category = 'FOREIGN KEY'\n",
    "             AND failed_rows = 0 THEN 'PASS'\n",
    "\n",
    "        WHEN dq_category = 'FOREIGN KEY'\n",
    "             AND failure_pct <= 0.1 THEN 'WARN'\n",
    "\n",
    "        WHEN dq_category = 'FOREIGN KEY'\n",
    "             AND failure_pct > 0.1 THEN 'FAIL'\n",
    "\n",
    "        ELSE 'REVIEW'\n",
    "    END AS status\n",
    "\n",
    "FROM dq_results\n",
    "ORDER BY\n",
    "    CASE dq_category\n",
    "        WHEN 'VOLUME' THEN 1\n",
    "        WHEN 'NULL' THEN 2\n",
    "        WHEN 'UNIQUE' THEN 3\n",
    "        WHEN 'TYPE / FORMAT' THEN 4\n",
    "        WHEN 'RANGE' THEN 5\n",
    "        WHEN 'SENTINEL' THEN 6\n",
    "        WHEN 'FOREIGN KEY' THEN 7\n",
    "        ELSE 8\n",
    "    END,\n",
    "    check_name;"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": null,
   "inputWidgetPreferences": null,
   "language": "sql",
   "notebookMetadata": {
    "pythonIndentUnit": 4,
    "sqlQueryOptions": {
     "applyAutoLimit": true,
     "catalog": "workspace",
     "metastore": null,
     "schema": "default"
    }
   },
   "notebookName": "check_student_info_bronze.sql.dbquery.ipynb",
   "widgets": {}
  },
  "language_info": {
   "name": "sql"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
