{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 104857600,
      "rowLimit": 1000
     },
     "inputWidgets": {},
     "nuid": "1fbdda92-1319-40c3-8ee5-552c3a663b6d",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "-- STUDENT ASSESSMENT BRONZE DATA QUALITY VALIDATION\n",
    "\n",
    "WITH duplicate_student_assessment AS (\n",
    "    -- Duplicate student-assessment business key\n",
    "    SELECT\n",
    "        id_assessment,\n",
    "        id_student,\n",
    "        COUNT(*) AS duplicate_count\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze\n",
    "    GROUP BY\n",
    "        id_assessment,\n",
    "        id_student\n",
    "    HAVING COUNT(*) > 1\n",
    "),\n",
    "\n",
    "duplicate_exact AS (\n",
    "    -- Exact duplicate records\n",
    "    SELECT\n",
    "        id_assessment,\n",
    "        id_student,\n",
    "        date_submitted,\n",
    "        is_banked,\n",
    "        score,\n",
    "        COUNT(*) AS duplicate_count\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze\n",
    "    GROUP BY\n",
    "        id_assessment,\n",
    "        id_student,\n",
    "        date_submitted,\n",
    "        is_banked,\n",
    "        score\n",
    "    HAVING COUNT(*) > 1\n",
    "),\n",
    "\n",
    "assessment_keys AS (\n",
    "    -- Distinct assessment identifiers for referential integrity\n",
    "    SELECT DISTINCT\n",
    "        TRY_CAST(id_assessment AS BIGINT) AS id_assessment\n",
    "    FROM oulad.oulad_bronze.assessment_bronze\n",
    "    WHERE TRY_CAST(id_assessment AS BIGINT) IS NOT NULL\n",
    "),\n",
    "\n",
    "student_keys AS (\n",
    "    -- Distinct student identifiers for referential integrity\n",
    "    SELECT DISTINCT\n",
    "        TRY_CAST(id_student AS BIGINT) AS id_student\n",
    "    FROM oulad.oulad_bronze.student_info_bronze\n",
    "    WHERE TRY_CAST(id_student AS BIGINT) IS NOT NULL\n",
    "),\n",
    "\n",
    "validation_results AS (\n",
    "\n",
    "    -- Volume check\n",
    "    SELECT\n",
    "        'student_assessment_bronze' AS table_name,\n",
    "        'Row count' AS check_name,\n",
    "        'VOLUME' AS dq_category,\n",
    "        COUNT(*) AS total_rows,\n",
    "        0 AS failed_rows,\n",
    "        0.00 AS failure_pct,\n",
    "        'Table should contain records' AS expected_value,\n",
    "        CASE\n",
    "            WHEN COUNT(*) > 0 THEN 'PASS'\n",
    "            ELSE 'FAIL'\n",
    "        END AS status\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- NULL checks\n",
    "    SELECT\n",
    "        'student_assessment_bronze',\n",
    "        'Missing id_assessment',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(id_assessment IS NULL),\n",
    "        ROUND(\n",
    "            COUNT_IF(id_assessment IS NULL) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        '0% missing; mandatory key',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(id_assessment IS NULL) = 0 THEN 'PASS'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_assessment_bronze',\n",
    "        'Missing id_student',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(id_student IS NULL),\n",
    "        ROUND(\n",
    "            COUNT_IF(id_student IS NULL) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        '0% missing; mandatory key',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(id_student IS NULL) = 0 THEN 'PASS'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_assessment_bronze',\n",
    "        'Missing date_submitted',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(date_submitted IS NULL),\n",
    "        ROUND(\n",
    "            COUNT_IF(date_submitted IS NULL) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'Submission date should normally be populated',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(date_submitted IS NULL) = 0 THEN 'PASS'\n",
    "            WHEN COUNT_IF(date_submitted IS NULL) * 100.0 / COUNT(*) <= 1\n",
    "                THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_assessment_bronze',\n",
    "        'Missing is_banked',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(is_banked IS NULL),\n",
    "        ROUND(\n",
    "            COUNT_IF(is_banked IS NULL) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'is_banked should be populated',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(is_banked IS NULL) = 0 THEN 'PASS'\n",
    "            WHEN COUNT_IF(is_banked IS NULL) * 100.0 / COUNT(*) <= 1\n",
    "                THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_assessment_bronze',\n",
    "        'Missing score',\n",
    "        'NULL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(score IS NULL),\n",
    "        ROUND(\n",
    "            COUNT_IF(score IS NULL) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'Score should normally be populated',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(score IS NULL) = 0 THEN 'PASS'\n",
    "            WHEN COUNT_IF(score IS NULL) * 100.0 / COUNT(*) <= 1\n",
    "                THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- Uniqueness checks\n",
    "    SELECT\n",
    "        'student_assessment_bronze',\n",
    "        'Duplicate student-assessment business key',\n",
    "        'UNIQUE',\n",
    "        COUNT(*),\n",
    "        COALESCE(\n",
    "            (\n",
    "                SELECT SUM(duplicate_count - 1)\n",
    "                FROM duplicate_student_assessment\n",
    "            ),\n",
    "            0\n",
    "        ),\n",
    "        ROUND(\n",
    "            COALESCE(\n",
    "                (\n",
    "                    SELECT SUM(duplicate_count - 1)\n",
    "                    FROM duplicate_student_assessment\n",
    "                ),\n",
    "                0\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        '0% duplicate id_assessment + id_student',\n",
    "        CASE\n",
    "            WHEN COALESCE(\n",
    "                (\n",
    "                    SELECT SUM(duplicate_count - 1)\n",
    "                    FROM duplicate_student_assessment\n",
    "                ),\n",
    "                0\n",
    "            ) = 0 THEN 'PASS'\n",
    "            WHEN COALESCE(\n",
    "                (\n",
    "                    SELECT SUM(duplicate_count - 1)\n",
    "                    FROM duplicate_student_assessment\n",
    "                ),\n",
    "                0\n",
    "            ) * 100.0 / COUNT(*) <= 1 THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_assessment_bronze',\n",
    "        'Exact duplicate records',\n",
    "        'UNIQUE',\n",
    "        COUNT(*),\n",
    "        COALESCE(\n",
    "            (\n",
    "                SELECT SUM(duplicate_count - 1)\n",
    "                FROM duplicate_exact\n",
    "            ),\n",
    "            0\n",
    "        ),\n",
    "        ROUND(\n",
    "            COALESCE(\n",
    "                (\n",
    "                    SELECT SUM(duplicate_count - 1)\n",
    "                    FROM duplicate_exact\n",
    "                ),\n",
    "                0\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        '0% duplicate records',\n",
    "        CASE\n",
    "            WHEN COALESCE(\n",
    "                (\n",
    "                    SELECT SUM(duplicate_count - 1)\n",
    "                    FROM duplicate_exact\n",
    "                ),\n",
    "                0\n",
    "            ) = 0 THEN 'PASS'\n",
    "            WHEN COALESCE(\n",
    "                (\n",
    "                    SELECT SUM(duplicate_count - 1)\n",
    "                    FROM duplicate_exact\n",
    "                ),\n",
    "                0\n",
    "            ) * 100.0 / COUNT(*) <= 1 THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- Type and format checks\n",
    "    SELECT\n",
    "        'student_assessment_bronze',\n",
    "        'Invalid id_assessment format',\n",
    "        'TYPE / FORMAT',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(\n",
    "            id_assessment IS NOT NULL\n",
    "            AND TRY_CAST(id_assessment AS BIGINT) IS NULL\n",
    "        ),\n",
    "        ROUND(\n",
    "            COUNT_IF(\n",
    "                id_assessment IS NOT NULL\n",
    "                AND TRY_CAST(id_assessment AS BIGINT) IS NULL\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'id_assessment must be numeric',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(\n",
    "                id_assessment IS NOT NULL\n",
    "                AND TRY_CAST(id_assessment AS BIGINT) IS NULL\n",
    "            ) = 0 THEN 'PASS'\n",
    "            WHEN COUNT_IF(\n",
    "                id_assessment IS NOT NULL\n",
    "                AND TRY_CAST(id_assessment AS BIGINT) IS NULL\n",
    "            ) * 100.0 / COUNT(*) <= 1 THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_assessment_bronze',\n",
    "        'Invalid id_student format',\n",
    "        'TYPE / FORMAT',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(\n",
    "            id_student IS NOT NULL\n",
    "            AND TRY_CAST(id_student AS BIGINT) IS NULL\n",
    "        ),\n",
    "        ROUND(\n",
    "            COUNT_IF(\n",
    "                id_student IS NOT NULL\n",
    "                AND TRY_CAST(id_student AS BIGINT) IS NULL\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'id_student must be numeric',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(\n",
    "                id_student IS NOT NULL\n",
    "                AND TRY_CAST(id_student AS BIGINT) IS NULL\n",
    "            ) = 0 THEN 'PASS'\n",
    "            WHEN COUNT_IF(\n",
    "                id_student IS NOT NULL\n",
    "                AND TRY_CAST(id_student AS BIGINT) IS NULL\n",
    "            ) * 100.0 / COUNT(*) <= 1 THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_assessment_bronze',\n",
    "        'Invalid date_submitted format',\n",
    "        'TYPE / FORMAT',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(\n",
    "            date_submitted IS NOT NULL\n",
    "            AND TRY_CAST(date_submitted AS BIGINT) IS NULL\n",
    "        ),\n",
    "        ROUND(\n",
    "            COUNT_IF(\n",
    "                date_submitted IS NOT NULL\n",
    "                AND TRY_CAST(date_submitted AS BIGINT) IS NULL\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'date_submitted must be numeric',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(\n",
    "                date_submitted IS NOT NULL\n",
    "                AND TRY_CAST(date_submitted AS BIGINT) IS NULL\n",
    "            ) = 0 THEN 'PASS'\n",
    "            WHEN COUNT_IF(\n",
    "                date_submitted IS NOT NULL\n",
    "                AND TRY_CAST(date_submitted AS BIGINT) IS NULL\n",
    "            ) * 100.0 / COUNT(*) <= 1 THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    SELECT\n",
    "        'student_assessment_bronze',\n",
    "        'Invalid is_banked format',\n",
    "        'TYPE / FORMAT',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(\n",
    "            is_banked IS NOT NULL\n",
    "            AND TRY_CAST(is_banked AS INT) IS NULL\n",
    "        ),\n",
    "        ROUND(\n",
    "            COUNT_IF(\n",
    "                is_banked IS NOT NULL\n",
    "                AND TRY_CAST(is_banked AS INT) IS NULL\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'is_banked must be numeric',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(\n",
    "                is_banked IS NOT NULL\n",
    "                AND TRY_CAST(is_banked AS INT) IS NULL\n",
    "            ) = 0 THEN 'PASS'\n",
    "            WHEN COUNT_IF(\n",
    "                is_banked IS NOT NULL\n",
    "                AND TRY_CAST(is_banked AS INT) IS NULL\n",
    "            ) * 100.0 / COUNT(*) <= 1 THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- Source sentinel check\n",
    "    SELECT\n",
    "        'student_assessment_bronze',\n",
    "        'Source sentinel (?) in score',\n",
    "        'SENTINEL',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(score = '?'),\n",
    "        ROUND(\n",
    "            COUNT_IF(score = '?') * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'Source may use ? for unavailable score',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(score = '?') = 0 THEN 'PASS'\n",
    "            ELSE 'WARN'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- Score range check\n",
    "    SELECT\n",
    "        'student_assessment_bronze',\n",
    "        'Score outside valid range',\n",
    "        'RANGE',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(\n",
    "            TRY_CAST(score AS DOUBLE) IS NOT NULL\n",
    "            AND (\n",
    "                TRY_CAST(score AS DOUBLE) < 0\n",
    "                OR TRY_CAST(score AS DOUBLE) > 100\n",
    "            )\n",
    "        ),\n",
    "        ROUND(\n",
    "            COUNT_IF(\n",
    "                TRY_CAST(score AS DOUBLE) IS NOT NULL\n",
    "                AND (\n",
    "                    TRY_CAST(score AS DOUBLE) < 0\n",
    "                    OR TRY_CAST(score AS DOUBLE) > 100\n",
    "                )\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        '0 <= score <= 100',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(\n",
    "                TRY_CAST(score AS DOUBLE) IS NOT NULL\n",
    "                AND (\n",
    "                    TRY_CAST(score AS DOUBLE) < 0\n",
    "                    OR TRY_CAST(score AS DOUBLE) > 100\n",
    "                )\n",
    "            ) = 0 THEN 'PASS'\n",
    "            WHEN COUNT_IF(\n",
    "                TRY_CAST(score AS DOUBLE) IS NOT NULL\n",
    "                AND (\n",
    "                    TRY_CAST(score AS DOUBLE) < 0\n",
    "                    OR TRY_CAST(score AS DOUBLE) > 100\n",
    "                )\n",
    "            ) * 100.0 / COUNT(*) <= 1 THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- Accepted value check\n",
    "    SELECT\n",
    "        'student_assessment_bronze',\n",
    "        'Invalid is_banked value',\n",
    "        'ACCEPTED VALUE',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(\n",
    "            TRY_CAST(is_banked AS INT) IS NOT NULL\n",
    "            AND TRY_CAST(is_banked AS INT) NOT IN (0, 1)\n",
    "        ),\n",
    "        ROUND(\n",
    "            COUNT_IF(\n",
    "                TRY_CAST(is_banked AS INT) IS NOT NULL\n",
    "                AND TRY_CAST(is_banked AS INT) NOT IN (0, 1)\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'is_banked must be 0 or 1',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(\n",
    "                TRY_CAST(is_banked AS INT) IS NOT NULL\n",
    "                AND TRY_CAST(is_banked AS INT) NOT IN (0, 1)\n",
    "            ) = 0 THEN 'PASS'\n",
    "            WHEN COUNT_IF(\n",
    "                TRY_CAST(is_banked AS INT) IS NOT NULL\n",
    "                AND TRY_CAST(is_banked AS INT) NOT IN (0, 1)\n",
    "            ) * 100.0 / COUNT(*) <= 1 THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- Foreign key check to assessments\n",
    "    SELECT\n",
    "        'student_assessment_bronze',\n",
    "        'Assessment without matching assessment definition',\n",
    "        'FOREIGN KEY',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(\n",
    "            sa.id_assessment IS NOT NULL\n",
    "            AND ak.id_assessment IS NULL\n",
    "        ),\n",
    "        ROUND(\n",
    "            COUNT_IF(\n",
    "                sa.id_assessment IS NOT NULL\n",
    "                AND ak.id_assessment IS NULL\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'Every id_assessment should exist in assessment_bronze',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(\n",
    "                sa.id_assessment IS NOT NULL\n",
    "                AND ak.id_assessment IS NULL\n",
    "            ) = 0 THEN 'PASS'\n",
    "            WHEN COUNT_IF(\n",
    "                sa.id_assessment IS NOT NULL\n",
    "                AND ak.id_assessment IS NULL\n",
    "            ) * 100.0 / COUNT(*) <= 0.1 THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze sa\n",
    "    LEFT JOIN assessment_keys ak\n",
    "        ON TRY_CAST(sa.id_assessment AS BIGINT) = ak.id_assessment\n",
    "\n",
    "    UNION ALL\n",
    "\n",
    "    -- Foreign key check to student information\n",
    "    SELECT\n",
    "        'student_assessment_bronze',\n",
    "        'Assessment without matching student',\n",
    "        'FOREIGN KEY',\n",
    "        COUNT(*),\n",
    "        COUNT_IF(\n",
    "            sa.id_student IS NOT NULL\n",
    "            AND sk.id_student IS NULL\n",
    "        ),\n",
    "        ROUND(\n",
    "            COUNT_IF(\n",
    "                sa.id_student IS NOT NULL\n",
    "                AND sk.id_student IS NULL\n",
    "            ) * 100.0 / COUNT(*),\n",
    "            2\n",
    "        ),\n",
    "        'Every id_student should exist in student_info_bronze',\n",
    "        CASE\n",
    "            WHEN COUNT_IF(\n",
    "                sa.id_student IS NOT NULL\n",
    "                AND sk.id_student IS NULL\n",
    "            ) = 0 THEN 'PASS'\n",
    "            WHEN COUNT_IF(\n",
    "                sa.id_student IS NOT NULL\n",
    "                AND sk.id_student IS NULL\n",
    "            ) * 100.0 / COUNT(*) <= 0.1 THEN 'WARN'\n",
    "            ELSE 'FAIL'\n",
    "        END\n",
    "    FROM oulad.oulad_bronze.student_assessment_bronze sa\n",
    "    LEFT JOIN student_keys sk\n",
    "        ON TRY_CAST(sa.id_student AS BIGINT) = sk.id_student\n",
    ")\n",
    "\n",
    "SELECT\n",
    "    table_name,\n",
    "    check_name,\n",
    "    dq_category,\n",
    "    total_rows,\n",
    "    failed_rows,\n",
    "    failure_pct,\n",
    "    expected_value,\n",
    "    status\n",
    "FROM validation_results\n",
    "ORDER BY\n",
    "    CASE dq_category\n",
    "        WHEN 'VOLUME' THEN 1\n",
    "        WHEN 'NULL' THEN 2\n",
    "        WHEN 'UNIQUE' THEN 3\n",
    "        WHEN 'TYPE / FORMAT' THEN 4\n",
    "        WHEN 'SENTINEL' THEN 5\n",
    "        WHEN 'RANGE' THEN 6\n",
    "        WHEN 'ACCEPTED VALUE' THEN 7\n",
    "        WHEN 'FOREIGN KEY' THEN 8\n",
    "        ELSE 9\n",
    "    END,\n",
    "    check_name;"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": null,
   "inputWidgetPreferences": null,
   "language": "sql",
   "notebookMetadata": {
    "pythonIndentUnit": 4,
    "sqlQueryOptions": {
     "applyAutoLimit": true,
     "catalog": "workspace",
     "metastore": null,
     "schema": "default"
    }
   },
   "notebookName": "check_student_assessment_bronze.sql.dbquery.ipynb",
   "widgets": {}
  },
  "language_info": {
   "name": "sql"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
